### ISSUE TITLE
你好，请问realsense输出.json文件呢？我这个问题可能有点低级，但是我真心求问

### ISSUE THREAD

**Issue by veryneo** [WenxingPeng/SLAM-project_Data-set-building#1]
我都是用ros录制bag文件来跑orb的，想请教下如何才能让相机输出.json文件呢？
这个问题有点低级，我自己搜了搜，确实没搜到，所以才冒昧向您提问的。

**Comment by veryneo** [comment]
json文件我查到的都是作为配置文件使用的

**Comment by WenxingPeng** [comment]
抱歉，因为疫情的原因，这个项目当时做的时候，是另一位同事将相机采集出来的数据传输给我的，至于如何用相机输出json格式的数据可以到网上查一下，或许用英文查找可以得到更加令你满意的答案！
